#!/usr/bin/env bash
# Runs knowledge-check.sh against fixture trees, one per invariant, and asserts both the exit code
# and the message. This is how the validator proves it can go red: a check that has never failed is
# not known to work, and a check that fails with the wrong message is not actionable.
#
#   bash .claude/tools/knowledge-check.test.sh
#
# Every case builds a real tree and runs the real validator. Nothing here greps the validator's
# source, because a test that reads the script instead of running it passes over a broken script.

unset MSYS_NO_PATHCONV
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KC="$HERE/knowledge-check.sh"
[ -f "$KC" ] || { echo "knowledge-check.sh not found beside this suite"; exit 1; }
T="$(mktemp -d 2>/dev/null || mktemp -d -t kctest)"
trap 'rm -rf "$T"' EXIT

fails=0; total=0; got=""

hdr() {   # file title -> a page carrying the header the rules require
  cat > "$1" <<EOF
---
title: $2
status: verified
as_of: 2026-09-19
last_verified: 2026-09-19
verification_method: Generated by knowledge-check.test.sh and read by the validator under test
scope: This fixture only
confidence: High. The fixture is generated from this file
known_gaps: It is a fixture, so it settles nothing about the real base
reverify_when: On any change to knowledge-check.sh
---

# $2
EOF
}

mk() {   # build a valid project root at $1
  local r="$1" kb="$1/docs/knowledge-base"
  rm -rf "$r"; mkdir -p "$kb/00-orientation" "$kb/_readings" "$r/.claude/tools"
  printf '# Knowledge base\n\nNo header here by design: the rules give this file another shape.\n' > "$kb/README.md"
  printf '# Pending\n\n- `P2` one line, no header, by design.\n' > "$kb/99-pending.md"
  hdr "$kb/00-orientation/index.md" "Where every page is"
  hdr "$kb/_readings/study.md" "What an external source says"
  cat > "$kb/decisions.md" <<'EOF'
---
title: Every decision in force
status: verified
as_of: 2026-09-19
last_verified: 2026-09-19
verification_method: Generated by knowledge-check.test.sh
scope: This fixture only
confidence: High. The fixture is generated
known_gaps: It is a fixture
reverify_when: On any change to knowledge-check.sh
---

## Decisions in force

### D-02 - The second decision
**Decision:** something. **Supersedes:** S-01.

### D-01 - The first decision
**Decision:** something else.

## Superseded

| Code | What it was | Replaced by |
|---|---|---|
| S-01 | the old way | D-02 |
EOF
  # references that must resolve, in each supported form
  {
    printf 'A link to [the decisions page](../decisions.md) and to [the index](index.md).\n'
    printf 'A backticked page-relative reference to `../decisions.md`.\n'
    printf 'An external link to [a site](https://example.invalid/gone) is never fetched.\n'
    printf 'A link with an anchor, [decisions](../decisions.md#d-01), and a space, [x](../a%%20b.md).\n'
  } >> "$kb/00-orientation/index.md"
  printf 'a b\n' > "$kb/a b.md"          # the %20 target above
  hdr "$T/tmp-ab" "x"; cat "$T/tmp-ab" > "$kb/a b.md"
}

run() { got="$(bash "$KC" "$1" >"$T/out" 2>&1; echo $?)"; }

check() {   # name expected-exit needle
  total=$((total+1))
  if [ "$got" != "$2" ]; then
    printf '  FAIL  %-56s expected exit %s got %s\n' "$1" "$2" "$got"; fails=$((fails+1))
    sed 's/^/          /' "$T/out" | head -6; return
  fi
  if [ -n "$3" ] && ! grep -qF -e "$3" "$T/out"; then
    printf '  FAIL  %-56s exit %s, no message matching: %s\n' "$1" "$got" "$3"; fails=$((fails+1))
    sed 's/^/          /' "$T/out" | head -6; return
  fi
  printf '  ok    %-56s exit %s\n' "$1" "$got"
}

R="$T/p"; KB="$R/docs/knowledge-base"

echo "valid knowledge base, and the exemptions"
mk "$R"; run "$R"; check "a valid base passes"                       0 "PASS  page header schema"
mk "$R"; run "$R"; check "README.md and 99-pending.md need no header" 0 "pages=4"
mk "$R"; printf 'x\n' > "$KB/_readings/nested.md"; run "$R"
check "a new page anywhere in the base is in scope"                  1 "no page header"
mk "$R"; printf '# not the base README\n' > "$R/README.md"; run "$R"
check "a README outside the base is not a knowledge page"            0 "PASS  page header schema"

echo "required metadata"
for f in title status as_of last_verified verification_method scope confidence known_gaps reverify_when; do
  mk "$R"; grep -v "^$f:" "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
  run "$R"; check "missing required field: $f"                       1 "missing required field: $f"
done
mk "$R"; sed 's/^known_gaps:.*/known_gaps:/' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "a required field present but empty"                 1 "required field is empty: known_gaps"
mk "$R"; printf '# no front matter at all\n' > "$KB/_readings/study.md"
run "$R"; check "a page with no front matter block"                  1 "no page header"
# Last-wins would be a hole: a second copy of a key further down could repair an invalid header,
# and a stray --- rule in the body would close the block so the page still looked well formed.
mk "$R"; sed 's/^status: verified/status: bogus-value/' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
awk '{ print } /^reverify_when:/ { print "status: verified" }' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "a key set twice cannot repair an invalid value"     1 "sets status more than once"
mk "$R"; run "$R"; check "and the same page without the repeat is fine" 0 "PASS  page header schema"
mk "$R"
{ sed 's/^status: verified/status: bogus-value/' "$KB/_readings/study.md" | grep -v '^---$' | head -20
  printf 'status: verified\n\n---\n\nbody after a horizontal rule\n'; } > "$T/x"
{ printf -- '---\n'; cat "$T/x"; } > "$KB/_readings/study.md"
run "$R"; check "a stray --- rule cannot close a header for free"    1 "more than once"
mk "$R"; grep -v '^---$' "$KB/_readings/study.md" > "$T/x"; { printf -- '---\n'; cat "$T/x"; } > "$KB/_readings/study.md"
run "$R"; check "a header opened and never closed"                   1 "never closed"
mk "$R"; printf -- '---\n' > "$KB/_readings/study.md"
run "$R"; check "a page that is only an opening fence"               1 "never closed"
mk "$R"; : > "$KB/_readings/study.md"
run "$R"; check "an empty page"                                      1 "the page is empty"

echo "controlled vocabularies"
mk "$R"; sed 's/^status: .*/status: mostly-right/' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "status outside the four defined values"             1 "status is not one of the four values"
for v in draft verified partially-verified superseded; do
  mk "$R"; sed "s/^status: .*/status: $v/" "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
  run "$R"; check "status $v is accepted"                            0 ""
done
mk "$R"; sed 's/^confidence: .*/confidence: Pretty sure/' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "confidence not starting High, Medium, or Low"       1 "confidence does not start with High, Medium, or Low"

echo "dates"
mk "$R"; sed 's/^last_verified: .*/last_verified: recently/' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "last_verified: recently"                            1 "last_verified is not a calendar date"
mk "$R"; sed 's/^as_of: .*/as_of: 19-09-2026/' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "a date in the wrong order of fields"                1 "as_of is not a calendar date"
mk "$R"; sed 's/^as_of: .*/as_of: 2026-02-30/' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "a day that does not exist in that month"            1 "as_of is not a calendar date"
mk "$R"; sed 's/^as_of: .*/as_of: 2026-13-01/' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "a month of 13"                                      1 "as_of is not a calendar date"
mk "$R"; sed 's/^as_of: .*/as_of: 2024-02-29/' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "a leap day in a leap year is accepted"              0 ""
mk "$R"; sed 's/^as_of: .*/as_of: 2026-02-29/' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "a leap day in a common year"                        1 "as_of is not a calendar date"
mk "$R"; sed 's/^last_verified: .*/last_verified: 2026-08-01/' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "last_verified before as_of"                         1 "is before as_of"

echo "local links and page-relative references"
mk "$R"; printf 'A [dead link](../decisions-old.md).\n' >> "$KB/00-orientation/index.md"
run "$R"; check "a broken local Markdown link"                       1 "broken local link: ../decisions-old.md"
mk "$R"; printf 'A [dead anchor link](../decisions-old.md#x).\n' >> "$KB/00-orientation/index.md"
run "$R"; check "a broken link carrying an anchor"                   1 "broken local link: ../decisions-old.md#x"
mk "$R"; printf 'A broken backtick reference to `../gone.md`.\n' >> "$KB/00-orientation/index.md"
run "$R"; check "a broken page-relative backtick reference"          1 "broken page-relative reference: ../gone.md"
mk "$R"; printf 'A template `../<date>-<name>/methodology.md` is not a reference.\n' >> "$KB/00-orientation/index.md"
run "$R"; check "a template in angle brackets is not checked"        0 ""
mk "$R"; printf 'The forms are `repo:<path>`, `commit:<sha>`, and [text](<target>).\n' >> "$KB/_readings/study.md"
run "$R"; check "a template in every citation form is not checked"   0 ""
mk "$R"; printf 'The syntax is `[label](some-target.md)`, quoted as an example.\n' >> "$KB/_readings/study.md"
run "$R"; check "a Markdown link inside backticks is an example"     0 ""
mk "$R"; printf 'The syntax is `[label](x.md)`, and a real [dead one](gone-for-good.md) beside it.\n' >> "$KB/_readings/study.md"
run "$R"; check "an unbackticked link on such a page still counts"   1 "broken local link: gone-for-good.md"
mk "$R"; printf 'Bare `decisions.md` and `.claude/x.sh` are prose, not references.\n' >> "$KB/_readings/study.md"
run "$R"; check "a bare backticked path is left alone"               0 ""
mk "$R"; { printf 'Fenced example:\n\n```\n'; printf 'A [dead link](../nope.md) inside a fence.\n'; printf '```\n'; } >> "$KB/_readings/study.md"
run "$R"; check "a link inside a fenced block is an example"         0 ""

echo "explicit evidence citations"
mk "$R"; printf 'Evidence: `repo:.claude/tools/knowledge-check.sh` is missing here.\n' >> "$KB/_readings/study.md"
run "$R"; check "a repo: path that does not exist"                   1 "referenced repository path does not exist"
mk "$R"; mkdir -p "$R/src"; printf 'x\n' > "$R/src/real.ts"
printf 'Evidence: `repo:src/real.ts`.\n' >> "$KB/_readings/study.md"
run "$R"; check "a repo: path that exists"                           0 ""
gitify() {   # make the fixture a checkout with one commit, and echo its short sha
  git -C "$R" init -q >/dev/null 2>&1
  git -C "$R" config user.email t@example.invalid >/dev/null 2>&1
  git -C "$R" config user.name t >/dev/null 2>&1
  git -C "$R" add -A >/dev/null 2>&1
  git -C "$R" commit -qm fixture >/dev/null 2>&1
  git -C "$R" rev-parse --short=7 HEAD 2>/dev/null
}
mk "$R"; printf 'Evidence: `commit:deadbee`.\n' >> "$KB/_readings/study.md"; gitify >/dev/null
run "$R"; check "a commit: that does not resolve"                    1 "referenced commit does not resolve: deadbee"
mk "$R"; sha="$(gitify)"; printf 'Evidence: `commit:%s`.\n' "$sha" >> "$KB/_readings/study.md"
run "$R"; check "a commit: that resolves in this checkout"           0 ""
mk "$R"; printf 'Evidence: `commit:zzzzzzz`.\n' >> "$KB/_readings/study.md"; gitify >/dev/null
run "$R"; check "a commit: that is not hexadecimal"                  1 "commit reference is not a hex sha: zzzzzzz"
mk "$R"; printf 'A bare `7f8620b` in prose is not a citation.\n' >> "$KB/_readings/study.md"
run "$R"; check "a bare hex string is left alone"                    0 ""

echo "supersession"
mk "$R"; sed 's|^scope: .*|scope: x\nsupersedes: ../gone.md|' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "supersedes names a page that does not exist"        1 "supersedes names a page that does not exist"
mk "$R"; sed 's|^scope: .*|scope: x\nsupersedes: study.md|' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "a page that supersedes itself"                      1 "supersedes points at this same page"
mk "$R"; sed 's|^scope: .*|scope: x\nsupersedes: ../decisions.md|' "$KB/_readings/study.md" > "$T/x" && mv "$T/x" "$KB/_readings/study.md"
run "$R"; check "supersedes naming a page that exists"               0 ""
mk "$R"; printf 'This rests on `D-99`, which was never decided.\n' >> "$KB/_readings/study.md"
run "$R"; check "citing a decision that is not defined"              1 "cites a decision that decisions.md does not define: D-99"
mk "$R"; sed 's/\*\*Supersedes:\*\* S-01./**Supersedes:** D-02./' "$KB/decisions.md" > "$T/x" && mv "$T/x" "$KB/decisions.md"
run "$R"; check "a decision that supersedes itself"                  1 "decision supersedes itself: D-02"

echo "curated documentation drift"
drift() {   # write a conf and a README stating $1
  mkdir -p "$R/.claude/skills/one" "$R/.claude/skills/two"
  printf 'Two skills, %s hooks.\n' "$1" > "$R/README.md"
  mkdir -p "$R/.claude/hooks"; : > "$R/.claude/hooks/a.sh"; : > "$R/.claude/hooks/a.ps1"
  printf 'stems .claude/hooks :: README.md :: [a-z]+ hooks\n' > "$R/.claude/knowledge-drift.conf"
}
mk "$R"; drift one;   run "$R"; check "a documented count that agrees with the tree"  0 "counts agree with the tree (1)"
mk "$R"; drift three; run "$R"; check "a documented count that disagrees"             1 "states 3 for stems .claude/hooks, the tree has 1"
mk "$R"; drift one; printf 'stems .claude/hooks :: README.md :: [a-z]+ widgets\n' > "$R/.claude/knowledge-drift.conf"
run "$R"; check "a curated pattern that matches nothing"                             1 "no sentence states"
mk "$R"; drift one; printf 'starcount .claude/hooks :: README.md :: [a-z]+ hooks\n' > "$R/.claude/knowledge-drift.conf"
run "$R"; check "an unknown derived quantity"                                        1 "unknown derived quantity: starcount"
mk "$R"; drift one; printf 'stems .claude/nope :: README.md :: [a-z]+ hooks\n' > "$R/.claude/knowledge-drift.conf"
run "$R"; check "a derived source that does not exist"                               1 "cannot derive stems"
mk "$R"; run "$R"; check "no conf means no drift checks, not a silent pass"           0 "no drift checks are curated"
mk "$R"; drift one; printf '# every line is a comment\n' > "$R/.claude/knowledge-drift.conf"
run "$R"; check "a curated list that produces no check at all"                       1 "produced no checks at all"
mk "$R"; drift one; printf 'stems .claude/hooks :: README.md :: [a-z-]+ hooks' > "$R/.claude/knowledge-drift.conf"
run "$R"; check "a conf whose last line has no newline is still read"                0 "counts agree with the tree (1)"
mk "$R"; drift one
printf 'Twenty-one hooks, allegedly.\n' > "$R/README.md"
printf 'stems .claude/hooks :: README.md :: [A-Za-z-]+ hooks\n' > "$R/.claude/knowledge-drift.conf"
run "$R"; check "a hyphenated number is read as itself, not its last word" 1 "states 21 for stems .claude/hooks, the tree has 1"

echo "line endings"
mk "$R"; awk '{ printf "%s\r\n", $0 }' "$KB/_readings/study.md" > "$T/crlf" && mv "$T/crlf" "$KB/_readings/study.md"
run "$R"; check "a page with CRLF endings is read the same way"                      0 "PASS  page header schema"
mk "$R"; awk '{ printf "%s\r\n", $0 }' "$KB/_readings/study.md" | sed 's/^status: verified/status: nonsense/' > "$T/crlf" && mv "$T/crlf" "$KB/_readings/study.md"
run "$R"; check "and a CRLF page is still checked, not waved through"                1 "status is not one of the four values"

# Shape B: the base sits at knowledge-base/ at a workspace root above the clones, repo: is a path
# from that root, and commit: is resolved against every checkout layout.sh reports. A layout that
# is reasoned about and never run is not tested, so this one is run.
echo "shape B, a workspace above several checkouts"
W="$T/ws"; rm -rf "$W"
mkdir -p "$W/knowledge-base/_readings" "$W/repos/one" "$W/.claude/tools"
cp "$HERE/layout.sh" "$W/.claude/tools/layout.sh"
git -C "$W/repos/one" init -q 2>/dev/null
printf 'x\n' > "$W/repos/one/f.txt"
git -C "$W/repos/one" -c user.email=t@t -c user.name=t add -A >/dev/null 2>&1
git -C "$W/repos/one" -c user.email=t@t -c user.name=t commit -qm one >/dev/null 2>&1
printf 'WS_REPOS=%s\n' "$W/repos" > "$W/.workspace"
printf '# kb\n' > "$W/knowledge-base/README.md"
printf '# pending\n' > "$W/knowledge-base/99-pending.md"
wsha="$(git -C "$W/repos/one" rev-parse --short=7 HEAD 2>/dev/null)"
wpage="$W/knowledge-base/_readings/a.md"
hdr "$wpage" "A workspace page"
printf 'Evidence: `commit:%s` and `repo:repos/one/f.txt`.\n' "$wsha" >> "$wpage"
got="$(bash "$KC" "$W" >"$T/out" 2>&1; echo $?)"
check "the base is found at knowledge-base/ and the shape is B" 0 "shape=B"
got="$(bash "$KC" "$W" >"$T/out" 2>&1; echo $?)"
check "repo: and commit: resolve from the workspace root"       0 "references resolve (2 checked)"
sed "s/commit:$wsha/commit:deadbee/" "$wpage" > "$T/x" && mv "$T/x" "$wpage"
got="$(bash "$KC" "$W" >"$T/out" 2>&1; echo $?)"
check "a commit in no checkout of the workspace fails"          1 "referenced commit does not resolve: deadbee"
printf 'Evidence: `repo:repos/one/missing.txt`.\n' >> "$wpage"
got="$(bash "$KC" "$W" >"$T/out" 2>&1; echo $?)"
check "a repo: path missing from the workspace fails"           1 "referenced repository path does not exist: repos/one/missing.txt"

echo "the base itself"
mk "$R"; rm -rf "$R/docs"; run "$R"; check "no knowledge base at all"                 1 "no knowledge base"
mk "$R"; rm -f "$KB"/*.md "$KB"/*/*.md; run "$R"; check "a base with no page at all"  1 "no Markdown page found"

echo
if [ "$fails" -eq 0 ]; then echo "  $total cases, 0 failed"; else echo "  $total cases, $fails FAILED"; fi
[ "$fails" -eq 0 ]
